default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: import_agent_development

test:
  <<: *default
  database: import_agent_test

production:
  <<: *default
  database: import_agent_production
  username: import_agent
  password: <%= ENV['IMPORT_AGENT_DATABASE_PASSWORD'] %>
